<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>VisorDatosSIG.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VisorDatosSIG.Domain\Domain.csproj" />
    <ProjectReference Include="..\VisorDatosSIG.Application\Application.csproj" />
    <ProjectReference Include="..\VisorDatosSIG.Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\VisorDatosSIG.Api\Api.csproj" />
  </ItemGroup>

</Project>
